app = "cockroachdb-example"

kill_signal = "SIGINT"
kill_timeout = 120

[checks]

  [checks.crdb_live]
    grace_period = "60s"
    interval = "10s"
    method = "get"
    path = "/health"
    port = 8080
    protocol = "https"
    timeout = "5s"
    tls_skip_verify = true
    type = "http"

[experimental]
  auto_rollback = false
  cmd = ["shell", "start_fly.sh"]
  private_network = true

[metrics]
  path = "/_status/vars"
  port = 8080

[[mounts]]
  destination = "/cockroach/cockroach-data"
  source = "crdb_data"

[[services]]
  internal_port = 26257
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 1000
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 10000

  [[services.tcp_checks]]
    grace_period = "60s"
    interval = 10000
    timeout = 5000
